dist: trusty
sudo: required

language: generic

services:
  - docker

env:
  global:
  - NJOBS="2"
  - MULTINOM_URL="https://github.com/math-comp/multinomials.git"
  - MULTINOM_VERSION="5b46e50983ee68dd1b6932e7e4a3bfc1113e7360"
  - PARAMCOQ_URL="https://github.com/aa755/paramcoq.git"
  matrix:
  - COQ_IMAGE="erikmd/coq:8.7.2_mathcomp-1.7.0" PARAMCOQ_VERSION="v1.1.0"
  - COQ_IMAGE="erikmd/coq:8.8.1_mathcomp-1.7.0" PARAMCOQ_VERSION="v1.1.0"

install: |
  # Prepare the coq-deps docker image with all dependencies
  # In case of no-output timeout, prepend "travis_wait" to:
  docker run --name=COQ ${COQ_IMAGE} /bin/bash --login -c "
    # this bash script is double-quoted to interpolate Travis CI env vars:
    echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -e # exit on failure
    set -x # trace for debug
    : Building coq-bignums...
    opam install -y -j ${NJOBS} coq-bignums
    opam config list && opam list
    : Building Multinomials...
    git clone -n ${MULTINOM_URL} ~coq/multinomials
    cd ~coq/multinomials
    git checkout ${MULTINOM_VERSION}
    make Makefile.coq && make -f Makefile.coq -j ${NJOBS} all && make install
    : Building Paramcoq...
    git clone -n ${PARAMCOQ_URL} ~coq/paramcoq
    cd ~coq/paramcoq
    git checkout ${PARAMCOQ_VERSION}
    make Makefile.coq && make -f Makefile.coq -j ${NJOBS} all && make install
    echo 'Install done.'"
  docker commit COQ coq-deps
  docker rm COQ

script:
- echo -e "${ANSI_YELLOW}Building CoqEAL...${ANSI_RESET}" && echo -en 'travis_fold:start:coqeal.build\\r'
- |
  docker run --rm -v ${TRAVIS_BUILD_DIR}:/home/coq/coqeal coq-deps /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -e # exit on failure
    set -x # trace for debug
    sudo chown -R coq:coq ~coq/coqeal
    cd ~coq/coqeal
    pushd theory && make Makefile.coq && make -f Makefile.coq -j ${NJOBS} all && make install && popd
    pushd refinements && make Makefile.coq && make -f Makefile.coq -j ${NJOBS} && make install && popd"
- echo -en 'travis_fold:end:coqeal.build\\r'
