dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=3
  - COMPILER="system"
  # system <=> 4.02.3
  - PARAMCOQ_URL="https://github.com/CohenCyril/paramcoq.git"
  - MULTINOM_URL="https://github.com/math-comp/multinomials.git"
  - MULTINOM_VERSION="5b46e50983ee68dd1b6932e7e4a3bfc1113e7360"
  - yellow="\\e[33;1m"
  - dflt="\\e[0m"
  matrix:
  - COQ_VERSION="8.6.1" MATHCOMP_VERSION="1.6.1" PARAMCOQ_VERSION="8dbf3fc1a0a0e0177eb9d88f6b76b8eb0dc22889"
  - COQ_VERSION="8.5.3" MATHCOMP_VERSION="1.6.1" PARAMCOQ_VERSION="956d77ff6269159be5828fe8235d2e0dfb1b5987"

matrix:
  allow_failures:
  - env: COQ_VERSION="8.5.3" MATHCOMP_VERSION="1.6.1" PARAMCOQ_VERSION="956d77ff6269159be5828fe8235d2e0dfb1b5987"
  # (refinements.v + Coq 8.5 => "Error: Unable to locate library ssrmatching.")

install:
- opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
- opam config env && eval $(opam config env)
- opam config var root
- opam repo add coq-released https://coq.inria.fr/opam/released || true
- opam update
- opam repo list
# The 'travis_wait' command below extends the 10 mn, no-output timeout to 20 mn
- |
  # Building Coq...
  travis_wait opam install -j ${NJOBS} -y ocamlfind camlp5 coq.${COQ_VERSION}

# The '-v' flag below is another solution to avoid the 10 mn, no-output timeout
- |
  # Building Mathcomp...
  opam install -j ${NJOBS} -y -v coq.${COQ_VERSION} coq-mathcomp-field.${MATHCOMP_VERSION}

- opam list
- |
  # Building Paramcoq...
  if [ -d paramcoq ] && [ -z "${PARAMCOQ_VERSION}" ]; then
      echo '# Building BUNDLED version of paramcoq...'
      pushd paramcoq && make Makefile.coq && make -f Makefile.coq -j ${NJOBS} all && make install && popd
  else
      echo '# CLONING and building paramcoq...'
      git clone --depth 50 -n ${PARAMCOQ_URL} $HOME/paramcoq
      if [ -n "${PARAMCOQ_VERSION}" ]; then
          pushd $HOME/paramcoq && git checkout ${PARAMCOQ_VERSION} && popd
      fi
      pushd $HOME/paramcoq && make Makefile.coq && make -f Makefile.coq -j ${NJOBS} all && make install && popd
  fi

- |
  # Building Multinomials...
  git clone --depth 50 -n ${MULTINOM_URL} $HOME/multinom
  pushd $HOME/multinom && git checkout ${MULTINOM_VERSION} && popd
  pushd $HOME/multinom && make Makefile.coq && make -f Makefile.coq -j ${NJOBS} all && make install && popd

script:
- echo -e "${yellow}Building CoqEAL...${dflt}" && echo -en 'travis_fold:start:coqeal.build\\r'
- pushd theory && make Makefile.coq && make -f Makefile.coq -j ${NJOBS} all && popd
- pushd refinements && make Makefile.coq && make -f Makefile.coq -j ${NJOBS} COQLIBS="-R ../theory CoqEAL.theory -R . CoqEAL.refinements" all && popd
- echo -en 'travis_fold:end:coqeal.build\\r'
